# Generated by Django 3.2.9 on 2021-11-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webboard', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
